services:
  site:
    build:
      context: .
      dockerfile: docker/Dockerfile.develop
    environment:
      - NODE_ENV=development
    command: npm run dev
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
        - action: sync
          path: ./public
          target: /app/public
        - action: rebuild
          path: ./package.json
        - action: rebuild
          path: ./package-lock.json
